name: ExoticGarden
version: '${version}'
author: TheBusyBiscuit, wdog5
description: A Slimefun Addon that adds new Plants and dishes to the game
website: https://github.com/MohistMC/ExoticGardenReborn

api-version: '1.20'
main: com.mohistmc.exoticgarden.ExoticGarden

depend:
  - Slimefun